### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by drewauff** [AmosNimos/change-directory-plus#1]
Getting error

`Missing dependency
Attempting to acquire missing dependency, please wait.
The missing dependency could not be acquired.
(Be sure to have pip3 installed)`

note: pip3 is installed.

**Comment by AmosNimos** [comment]
> Getting error
> 
> `Missing dependency Attempting to acquire missing dependency, please wait. The missing dependency could not be acquired. (Be sure to have pip3 installed)`
> 
> note: pip3 is installed.

Try typing the following in the terminal to see what dependency can't be acquired error message :
 pip3 install numpy
 pip3 install termcolor
 pip3 install curtsies

Eventually you could try with "sudo pip3 install"  or try to fix this problem without using sudo by ensuring that you have permissions to write to the directory that pip3 is set up to use.

**Comment by drewauff** [comment]
eventually got it going thanks 👍🏽
